"""empty message

Revision ID: 17358a2f6ddc
Revises: 120bf7db0da0
Create Date: 2024-12-17 15:54:48.350148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17358a2f6ddc'
down_revision: Union[str, None] = '120bf7db0da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('REBALANCING_RULES', sa.Column('issuer_type_id', sa.Integer(), nullable=True), schema='DRIX')
    op.add_column('REBALANCING_RULES', sa.Column('issuer_id', sa.Integer(), nullable=True), schema='DRIX')
    op.add_column('REBALANCING_RULES', sa.Column('type_rate_id', sa.Integer(), nullable=True), schema='DRIX')
    op.add_column('REBALANCING_RULES', sa.Column('currency_id', sa.Integer(), nullable=True), schema='DRIX')
    op.drop_constraint('FK__REBALANCI__type___6AE68A0E', 'REBALANCING_RULES', schema='DRIX', type_='foreignkey')
    op.drop_constraint('FK__REBALANCI__issue__68FE419C', 'REBALANCING_RULES', schema='DRIX', type_='foreignkey')
    op.drop_constraint('FK__REBALANCI__curre__6BDAAE47', 'REBALANCING_RULES', schema='DRIX', type_='foreignkey')
    op.drop_constraint('FK__REBALANCI__issue__69F265D5', 'REBALANCING_RULES', schema='DRIX', type_='foreignkey')
    op.create_foreign_key(None, 'REBALANCING_RULES', 'TIPO_TASA', ['type_rate_id'], ['ID'], source_schema='DRIX', referent_schema='MARKET')
    op.create_foreign_key(None, 'REBALANCING_RULES', 'EMISORES', ['issuer_id'], ['ID'], source_schema='DRIX', referent_schema='MARKET')
    op.create_foreign_key(None, 'REBALANCING_RULES', 'MONEDA', ['currency_id'], ['ID'], source_schema='DRIX', referent_schema='MARKET')
    op.create_foreign_key(None, 'REBALANCING_RULES', 'TIPO_EMISOR', ['issuer_type_id'], ['ID'], source_schema='DRIX', referent_schema='MARKET')
    op.drop_column('REBALANCING_RULES', 'currency', schema='DRIX')
    op.drop_column('REBALANCING_RULES', 'issuer_type', schema='DRIX')
    op.drop_column('REBALANCING_RULES', 'issuer', schema='DRIX')
    op.drop_column('REBALANCING_RULES', 'type_rate', schema='DRIX')
    op.add_column('SCHEDULE', sa.Column('rule_id', sa.Integer(), nullable=False), schema='DRIX')
    op.drop_constraint('FK__SCHEDULE__rule__02BE139F', 'SCHEDULE', schema='DRIX', type_='foreignkey')
    op.create_foreign_key(None, 'SCHEDULE', 'DATE_GENERATION_RULE', ['rule_id'], ['id'], source_schema='DRIX', referent_schema='DRIX')
    op.drop_column('SCHEDULE', 'rule', schema='DRIX')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SCHEDULE', sa.Column('rule', sa.INTEGER(), autoincrement=False, nullable=False), schema='DRIX')
    op.drop_constraint(None, 'SCHEDULE', schema='DRIX', type_='foreignkey')
    op.create_foreign_key('FK__SCHEDULE__rule__02BE139F', 'SCHEDULE', 'DATE_GENERATION_RULE', ['rule'], ['id'], source_schema='DRIX', referent_schema='DRIX')
    op.drop_column('SCHEDULE', 'rule_id', schema='DRIX')
    op.add_column('REBALANCING_RULES', sa.Column('type_rate', sa.INTEGER(), autoincrement=False, nullable=True), schema='DRIX')
    op.add_column('REBALANCING_RULES', sa.Column('issuer', sa.INTEGER(), autoincrement=False, nullable=True), schema='DRIX')
    op.add_column('REBALANCING_RULES', sa.Column('issuer_type', sa.INTEGER(), autoincrement=False, nullable=True), schema='DRIX')
    op.add_column('REBALANCING_RULES', sa.Column('currency', sa.INTEGER(), autoincrement=False, nullable=True), schema='DRIX')
    op.drop_constraint(None, 'REBALANCING_RULES', schema='DRIX', type_='foreignkey')
    op.drop_constraint(None, 'REBALANCING_RULES', schema='DRIX', type_='foreignkey')
    op.drop_constraint(None, 'REBALANCING_RULES', schema='DRIX', type_='foreignkey')
    op.drop_constraint(None, 'REBALANCING_RULES', schema='DRIX', type_='foreignkey')
    op.create_foreign_key('FK__REBALANCI__issue__69F265D5', 'REBALANCING_RULES', 'EMISORES', ['issuer'], ['ID'], source_schema='DRIX', referent_schema='MARKET')
    op.create_foreign_key('FK__REBALANCI__curre__6BDAAE47', 'REBALANCING_RULES', 'MONEDA', ['currency'], ['ID'], source_schema='DRIX', referent_schema='MARKET')
    op.create_foreign_key('FK__REBALANCI__issue__68FE419C', 'REBALANCING_RULES', 'TIPO_EMISOR', ['issuer_type'], ['ID'], source_schema='DRIX', referent_schema='MARKET')
    op.create_foreign_key('FK__REBALANCI__type___6AE68A0E', 'REBALANCING_RULES', 'TIPO_TASA', ['type_rate'], ['ID'], source_schema='DRIX', referent_schema='MARKET')
    op.drop_column('REBALANCING_RULES', 'currency_id', schema='DRIX')
    op.drop_column('REBALANCING_RULES', 'type_rate_id', schema='DRIX')
    op.drop_column('REBALANCING_RULES', 'issuer_id', schema='DRIX')
    op.drop_column('REBALANCING_RULES', 'issuer_type_id', schema='DRIX')
    # ### end Alembic commands ###
