"""empty message

Revision ID: c89aefd5c6ed
Revises: 17358a2f6ddc
Create Date: 2024-12-30 12:47:33.317353

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mssql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c89aefd5c6ed"
down_revision: str | None = "17358a2f6ddc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "REBALANCING_RULES",
        sa.Column(
            "amortization", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        schema="DRIX",
    )
    op.alter_column(
        "REBALANCING_RULES",
        "days_since_issued",
        existing_type=sa.INTEGER(),
        nullable=False,
        schema="DRIX",
    )
    op.alter_column(
        "REBALANCING_RULES",
        "days_until_maturity",
        existing_type=sa.INTEGER(),
        nullable=False,
        schema="DRIX",
    )
    op.alter_column(
        "REBALANCING_RULES",
        "minimum_outstanding",
        existing_type=sa.FLOAT(precision=53),
        nullable=False,
        schema="DRIX",
    )
    op.drop_column("REBALANCING_RULES", "type_amortizaton", schema="DRIX")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "REBALANCING_RULES",
        sa.Column("type_amortizaton", mssql.BIT(), autoincrement=False, nullable=True),
        schema="DRIX",
    )
    op.alter_column(
        "REBALANCING_RULES",
        "minimum_outstanding",
        existing_type=sa.FLOAT(precision=53),
        nullable=True,
        schema="DRIX",
    )
    op.alter_column(
        "REBALANCING_RULES",
        "days_until_maturity",
        existing_type=sa.INTEGER(),
        nullable=True,
        schema="DRIX",
    )
    op.alter_column(
        "REBALANCING_RULES",
        "days_since_issued",
        existing_type=sa.INTEGER(),
        nullable=True,
        schema="DRIX",
    )
    op.drop_column("REBALANCING_RULES", "amortization", schema="DRIX")
    # ### end Alembic commands ###
